POST https://onesignal.com/api/v1/notifications
Content-Type: application/json
Authorization: Basic OWFmZTc4MjItMDhlZC00ZGVkLTk2OTYtN2Y2YWYwMDdlODRi

{
  "app_id": "85680034-1987-4575-8f45-e2a6753f7e9e",
  "included_segments": ["All"],
  "contents": {
    "en": "Don't miss out! There's a match today at 12:45. Get ready to cheer for your team and enjoy the excitement!"
  },
  "large_icon": "https://tmssl.akamaized.net/images/flagge/head/107.png?lm=1520611569"
}

###
GET https://onesignal.com/api/v1/notifications?app_id=85680034-1987-4575-8f45-e2a6753f7e9e&limit=10&offset=0
Authorization: Basic OWFmZTc4MjItMDhlZC00ZGVkLTk2OTYtN2Y2YWYwMDdlODRi

###

POST http://localhost:8080/api/v1/movies
Content-Type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MThjMjY3Y2RkMmMwNWE0NzRiNmViZCIsImlhdCI6MTcwNjEwNDQ2Nn0.8w-C-eJRj3AFVeMAd6D-oqr472Kcc_OgJob-ti0VxCA

{
    "title": "test",
    "description": "qsdcqeedfqz",
    "thumbnail":"https://iconape.com/wp-content/files/dk/332067/png/bein-sport-1-logo.png",
    "link":"https://www.youtube.com/embed/AzOWzxJxxuA"
}


###

GET http://localhost:8080/api/v1/category